### ISSUE TITLE
Create meals

### ISSUE THREAD

**Issue by jpacsai** [jpacsai/gourmet-app#2]
- [x] - Create basic pages #4 
- [x] - Add types for basic `Meal` data structure #5
- [x] - Create mock meal data #6
- [x] - Create meal card #7
- [x] - Create QuickView overlay #15 
- [ ] - Add filters #8
- [ ] - Create meal page #9
- [ ] - Ability to edit existing meals #10
- [ ] - Ability to add new meals #11
