### ISSUE TITLE
Add filters to meals page

### ISSUE THREAD

**Issue by jpacsai** [jpacsai/gourmet-app#8]
- [x] - add Filter view
- [x] - clear filters UI
- [x] - clear filters - functionality #22 
- [x] - filter count #23 
- [ ] - FILTERS
   - [x] - time
   - [x] - temp
   - [x] - category?
   - [ ] - speed
   - [ ] - cost
   - [ ] - difficulty
   - [ ] - pre-cookable: checkbox
   - [ ] - freezable: checkbox
   - [ ] - likes?
   - [ ] - tags
   - [ ] - diet
